# golangci-lint configuration (v1 format)
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    # Essential linters
    - errcheck      # Check for unchecked errors
    - govet         # Report suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis checks
    - unused        # Check for unused code

    # Code quality
    - gosimple      # Simplify code
    - gofmt         # Check formatting
    - goimports     # Check imports are sorted
    - misspell      # Catch spelling mistakes
    - nilerr        # Check for nil error returns
    - nolintlint    # Check nolint directives are valid

    # Security
    - gosec         # Security checks

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      # Close methods - errors in defer are not actionable
      - (io.Closer).Close
      - (*os.File).Close
      - (*net.Conn).Close
      - (net.Conn).Close
      - (net.Listener).Close
      - (*net.TCPListener).Close
      - (*github.com/fsnotify/fsnotify.Watcher).Close
      # HTTP response writing
      - (net/http.ResponseWriter).Write
      # Output functions where error handling isn't meaningful
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Print
      - fmt.Printf
      - fmt.Println
      # OS cleanup operations that are best-effort
      - os.RemoveAll
      - os.Remove
      - os.Setenv

  gosec:
    excludes:
      - G104  # Audit errors not checked (we use errcheck for this)
      - G115  # Integer overflow conversion (false positive for port numbers)
      - G204  # Subprocess launched with variable (expected in CLI tools)
      - G304  # File path provided as taint input (expected in CLI tools)
      - G306  # WriteFile permissions (0644 is fine for config files)

  misspell:
    locale: US

  staticcheck:
    checks:
      - all

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - gosec
        - gofmt
        - goimports

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
