version: 2

project_name: grove

# Allow dirty git state because web dashboard is built during CI
git:
  ignore_tags:
    - menubar-*

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/grove
    binary: grove
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/iheanyi/grove/internal/cli.Version={{.Version}}
      - -X github.com/iheanyi/grove/internal/cli.Commit={{.ShortCommit}}
      - -X github.com/iheanyi/grove/internal/cli.Date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github

release:
  github:
    owner: iheanyi
    name: grove
  draft: false
  prerelease: auto

brews:
  - repository:
      owner: iheanyi
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/iheanyi/grove"
    description: "Development server manager for git worktrees"
    license: "MIT"
    install: |
      bin.install "grove"
    test: |
      system "#{bin}/grove", "version"
    # Skip Homebrew if token isn't set
    skip_upload: auto
